# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-01 14:53
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('action_function', models.CharField(max_length=128)),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', django.contrib.postgres.fields.jsonb.JSONField()),
                ('initial_state', django.contrib.postgres.fields.jsonb.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Condition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(max_length=128)),
                ('type', models.CharField(choices=[('E', 'Enable'), ('D', 'Disable')], max_length=1)),
                ('action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Action')),
            ],
        ),
        migrations.CreateModel(
            name='Data',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=128, null=True)),
                ('view', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False)),
                ('message_type', models.CharField(max_length=24)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('view', models.TextField(blank=True, null=True)),
                ('content', models.TextField()),
                ('section', models.CharField(default='default', max_length=128)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='workflow.Case')),
                ('origin', models.ManyToManyField(default=None, related_name='messages', to='workflow.Action')),
                ('response', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='caller', to='workflow.Data')),
            ],
        ),
        migrations.CreateModel(
            name='Workflow',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField()),
                ('group', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='auth.Group')),
            ],
        ),
        migrations.AddField(
            model_name='condition',
            name='data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflow.Data'),
        ),
        migrations.AddField(
            model_name='condition',
            name='workflow',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='case',
            name='data',
            field=models.ManyToManyField(blank=True, null=True, related_name='cases', to='workflow.Data'),
        ),
        migrations.AddField(
            model_name='case',
            name='workflow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cases', to='workflow.Workflow'),
        ),
        migrations.AddField(
            model_name='action',
            name='output',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='sources', to='workflow.Data'),
        ),
    ]
