# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 16:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0004_auto_20170502_1451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='case',
            name='parameter',
        ),
        migrations.AddField(
            model_name='case',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='cases', to='workflow.Parameter'),
        ),
    ]
