# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-04 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0008_auto_20170504_1321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='condition',
            name='action',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conditions', to='workflow.Action'),
        ),
    ]
