# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:47
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0010_auto_20170504_1352'),
    ]

    operations = [
        migrations.CreateModel(
            name='Value',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('value', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True)),
                ('case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workflow.Case')),
                ('parameter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='workflow.Parameter')),
            ],
        ),
    ]
