# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-08 17:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workflow', '0011_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='parameters',
            field=models.ManyToManyField(blank=True, related_name='workflows', to='workflow.Parameter'),
        ),
    ]
